[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "win32more"
version = "0.5.0"
dependencies = [
    "typing_extensions; python_version < '3.9'",
]

[tool.hatch.build]
only-include = ["win32more", "win32generator"]

[tool.hatch.envs.default]
dependencies = [
    "mypy",
]

[tool.hatch.envs.default.scripts]
typing = "mypy {args}"

[[tool.hatch.envs.hatch-test.matrix]]
python = [
    "3.12-64",
    "3.12-32",
    "3.11-64",
    "3.11-32",
    "3.10-64",
    "3.10-32",
    "3.9-64",
    "3.9-32",
    "3.8-64",
    "3.8-32",
    "3.7-64",
    "3.7-32",
]

# for 3.7: coverage[toml] fails to install
[tool.hatch.envs.hatch-test]
dependencies = [
    "pytest",
]

# for 3.7: pytest.exe fails with "SyntaxError: Non-UTF-8 code starting with '\x90' ..."
[tool.hatch.envs.hatch-test.scripts]
run = "python -m pytest {env:HATCH_TEST_ARGS:} {args}"

[tool.ruff]
line-length = 120
lint.select = ["E4", "E7", "E9", "F", "I"]

